name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          budgetPath: ./.github/workflows/lighthouse-budget.json # test performance budgets
          # uploadArtifacts: true # save results as an action artifacts
          # temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: ./.github/workflows/lighthouserc.json
      - name: List Files
        run: |
          pwd
          tree -d --noreport .
        