name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.lighthouse_context }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile
      - name: Build project
        run: |
          yarn build
      - name: Build Storybook
        run: |
          yarn build-storybook
      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@b4dfae3eb959c5226e2c5c6afd563d493188bfaf # 9.3.0
        with:
          budgetPath: ./.github/lighthouse-budget.json
          configPath: ./.github/lighthouserc.json
          uploadArtifacts: true

      - name: Output context
        id: output_context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "::set-output name=lighthouse_context::$GITHUB_CONTEXT"

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@7a5c598405937d486b0331594b5da2b14db670da # v6
        with:
          script: |
            const scoreEntry = (rawScore) => {
              const score = Math.round(rawScore * 100);
              const scoreIcon = score >= 90 ? '🟢' : score >= 50 ? '🟠' : '🔴';
              return `${scoreIcon} ${score}`;
            };

            console.log('n: ', ${{ needs.lighthouse.output1 }});
            
            const formatIndicators = (summary) => {
              const performance = scoreEntry(summary.performance);
              const accessibility = scoreEntry(summary.accessibility);
              const bestPractices = scoreEntry(summary['best-practices']);
              const seo = scoreEntry(summary.seo);
              const pwa = scoreEntry(summary.pwa);
              const linkToReport = `[report](https://github.com/okp4/ui/actions/runs/${{ needs.lighthouse.output1.lighthouse_context }})`;
              return [performance,accessibility,bestPractices,seo,pwa,linkToReport];
            };
            
            const formatRow = (items) => '| '+items.join(' | ')+' |';
            
            const results = ${{ steps.lighthouse_audit.outputs.manifest }};

            const rows = results.map(result => {
              const summary = result.summary;
              const indicators = formatIndicators(summary);
              return formatRow(indicators);
            });
            
            const header = formatRow(['Performance','Accessibility','Best Practices','SEO','PWA','Report']);
            const separator = formatRow(['---','---','---','---','---','---']);
            const comment = [ header, separator, ...rows ].join('\n');
            core.setOutput("comment", comment);

      - name: Add Lighthouse stats as comment
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443 # v2.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: lighthouse
          message: ${{ steps.format_lighthouse_score.outputs.comment }}
